# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8c1e8550e33a643ef4014f5b8f22283240037c6ba1d59cf26522a70047ac9a8ed7afc0f872e822597e0fe1d48c922bb0e6ab85191f56f820f0dd18d6e5b435

test:
  secret_key_base: 72384f81f75bdd2aedcde4878d647e5e70a5f6d67d44b5da4d38b20f55d66924b7c8ba1c8b03228ec52d2b24ddcf05ee4eb019a5114b047613326ca0a31fd3a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
